# Generated by Django 6.0 on 2025-12-06 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='image_patient',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='The phone number is in the wrong format. It should be in the format +998xxxxxxxxx only.', regex='^\\+998\\d{9}$')]),
        ),
    ]
